### ISSUE TITLE
undefined method tokens in version 0.1.30

### ISSUE THREAD

**Issue by m2omou** [lynndylanhurley/ng-token-auth#98]
I recently updated my Gemfile, and moved ng-token-auth to the version `0.1.30`:

But after that, I got a new error, saying "undefined method tokens". To make it work I had to go back to the previous version  `0.1.29`.

```log
NoMethodError (undefined method `tokens' for #<Resource:0x007fe722b7d598>):
  activemodel (4.1.6) lib/active_model/attribute_methods.rb:435:in `method_missing'
  activerecord (4.1.6) lib/active_record/attribute_methods.rb:211:in `method_missing'
  devise_token_auth (0.1.30) app/controllers/devise_token_auth/concerns/set_user_by_token.rb:103:in `is_batch_request?'
  devise_token_auth (0.1.30) app/controllers/devise_token_auth/concerns/set_user_by_token.rb:61:in `block in update_auth_header'
  activerecord (4.1.6) lib/active_record/locking/pessimistic.rb:72:in `block in with_lock'
  activerecord (4.1.6) lib/active_record/connection_adapters/abstract/database_statements.rb:201:in `block in transaction'
  activerecord (4.1.6) lib/active_record/connection_adapters/abstract/database_statements.rb:209:in `within_new_transaction'
  activerecord (4.1.6) lib/active_record/connection_adapters/abstract/database_statements.rb:201:in `transaction'
  activerecord (4.1.6) lib/active_record/transactions.rb:208:in `transaction'
  activerecord (4.1.6) lib/active_record/transactions.rb:259:in `transaction'
  activerecord (4.1.6) lib/active_record/locking/pessimistic.rb:70:in `with_lock'
  devise_token_auth (0.1.30) app/controllers/devise_token_auth/concerns/set_user_by_token.rb:57:in `update_auth_header'
  activesupport (4.1.6) lib/active_support/callbacks.rb:424:in `block in make_lambda'
  activesupport (4.1.6) lib/active_support/callbacks.rb:231:in `call'
```

Any ideas ? :)

**Comment by lynndylanhurley** [comment]
@m2omou - is the `tokens` column present on your user model?

**Comment by m2omou** [comment]
Yes I have the column token in my user model.

**Comment by lynndylanhurley** [comment]
That's strange. What does `Resource` refer to in the stacktrace above?

**Comment by booleanbetrayal** [comment]
closing due to lack of activity

**Comment by ajays1991** [comment]
i am also facing the similar issue here. 

Here is my application controller which adds the concern for set_user_token.

```
class AuthenticationController < ApplicationController
  include DeviseTokenAuth::Concerns::SetUserByToken
  before_action :authenticate_user!, if: :closed
  include ApplicationConcern
end

```
users table have a column named tokens.

For every other resource CRUD request i get the following error.
Authentication and API methods are working good but `after_action` method `update_auth_header` is trying to call attr_accessor on `@resource` for `tokens`.

Obviously `@resource` is other than user as this concern is included in base controller.
Error trace - 
```

NoMethodError (undefined method `tokens' for #<Integration:0x00000001686e28>):
  
activemodel (5.0.3) lib/active_model/attribute_methods.rb:433:in `method_missing'
devise_token_auth (0.1.42) app/controllers/devise_token_auth/concerns/set_user_by_token.rb:103:in `block in update_auth_header'
activerecord (5.0.3) lib/active_record/locking/pessimistic.rb:72:in `block in with_lock'
activerecord (5.0.3) lib/active_record/connection_adapters/abstract/database_statements.rb:232:in `block in transaction'
activerecord (5.0.3) lib/active_record/connection_adapters/abstract/transaction.rb:189:in `within_new_transaction'
activerecord (5.0.3) lib/active_record/connection_adapters/abstract/database_statements.rb:232:in `transaction'
activerecord (5.0.3) lib/active_record/transactions.rb:211:in `transaction'
activerecord (5.0.3) lib/active_record/transactions.rb:310:in `transaction'
activerecord (5.0.3) lib/active_record/locking/pessimistic.rb:70:in `with_lock'
devise_token_auth (0.1.42) app/controllers/devise_token_auth/concerns/set_user_by_token.rb:100:in `update_auth_header'
activesupport (5.0.3) lib/active_support/callbacks.rb:382:in `block in make_lambda'
activesupport (5.0.3) lib/active_support/callbacks.rb:218:in `block in halting'
activesupport (5.0.3) lib/active_support/callbacks.rb:456:in `block in call'
activesupport (5.0.3) lib/active_support/callbacks.rb:456:in `each'
activesupport (5.0.3) lib/active_support/callbacks.rb:456:in `call'
activesupport (5.0.3) lib/active_support/callbacks.rb:101:in `__run_callbacks__'
activesupport (5.0.3) lib/active_support/callbacks.rb:750:in `_run_process_action_callbacks'
activesupport (5.0.3) lib/active_support/callbacks.rb:90:in `run_callbacks'
actionpack (5.0.3) lib/abstract_controller/callbacks.rb:19:in `process_action'
actionpack (5.0.3) lib/action_controller/metal/rescue.rb:20:in `process_action'
actionpack (5.0.3) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
activesupport (5.0.3) lib/active_support/notifications.rb:164:in `block in instrument'
activesupport (5.0.3) lib/active_support/notifications/instrumenter.rb:21:in `instrument'
activesupport (5.0.3) lib/active_support/notifications.rb:164:in `instrument'
actionpack (5.0.3) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
actionpack (5.0.3) lib/action_controller/metal/params_wrapper.rb:248:in `process_action'
activerecord (5.0.3) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
actionpack (5.0.3) lib/abstract_controller/base.rb:126:in `process'
actionview (5.0.3) lib/action_view/rendering.rb:30:in `process'
actionpack (5.0.3) lib/action_controller/metal.rb:190:in `dispatch'
actionpack (5.0.3) lib/action_controller/metal.rb:262:in `dispatch'
actionpack (5.0.3) lib/action_dispatch/routing/route_set.rb:50:in `dispatch'
actionpack (5.0.3) lib/action_dispatch/routing/route_set.rb:32:in `serve'
actionpack (5.0.3) lib/action_dispatch/journey/router.rb:39:in `block in serve'
actionpack (5.0.3) lib/action_dispatch/journey/router.rb:26:in `each'
actionpack (5.0.3) lib/action_dispatch/journey/router.rb:26:in `serve'
actionpack (5.0.3) lib/action_dispatch/routing/route_set.rb:725:in `call'
warden (1.2.7) lib/warden/manager.rb:36:in `block in call'
warden (1.2.7) lib/warden/manager.rb:35:in `catch'
warden (1.2.7) lib/warden/manager.rb:35:in `call'
rack (2.0.3) lib/rack/etag.rb:25:in `call'
rack (2.0.3) lib/rack/conditional_get.rb:38:in `call'
rack (2.0.3) lib/rack/head.rb:12:in `call'
rack (2.0.3) lib/rack/session/abstract/id.rb:232:in `context'
rack (2.0.3) lib/rack/session/abstract/id.rb:226:in `call'
actionpack (5.0.3) lib/action_dispatch/middleware/cookies.rb:613:in `call'
activerecord (5.0.3) lib/active_record/migration.rb:553:in `call'
actionpack (5.0.3) lib/action_dispatch/middleware/callbacks.rb:38:in `block in call'
activesupport (5.0.3) lib/active_support/callbacks.rb:97:in `__run_callbacks__'
activesupport (5.0.3) lib/active_support/callbacks.rb:750:in `_run_call_callbacks'
activesupport (5.0.3) lib/active_support/callbacks.rb:90:in `run_callbacks'
actionpack (5.0.3) lib/action_dispatch/middleware/callbacks.rb:36:in `call'
actionpack (5.0.3) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.0.3) lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
actionpack (5.0.3) lib/action_dispatch/middleware/debug_exceptions.rb:49:in `call'
web-console (3.5.1) lib/web_console/middleware.rb:135:in `call_app'
web-console (3.5.1) lib/web_console/middleware.rb:28:in `block in call'
web-console (3.5.1) lib/web_console/middleware.rb:18:in `catch'
web-console (3.5.1) lib/web_console/middleware.rb:18:in `call'
actionpack (5.0.3) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
railties (5.0.3) lib/rails/rack/logger.rb:36:in `call_app'
railties (5.0.3) lib/rails/rack/logger.rb:24:in `block in call'
activesupport (5.0.3) lib/active_support/tagged_logging.rb:69:in `block in tagged'
activesupport (5.0.3) lib/active_support/tagged_logging.rb:26:in `tagged'
activesupport (5.0.3) lib/active_support/tagged_logging.rb:69:in `tagged'
railties (5.0.3) lib/rails/rack/logger.rb:24:in `call'
sprockets-rails (3.2.0) lib/sprockets/rails/quiet_assets.rb:13:in `call'
request_store (1.3.2) lib/request_store/middleware.rb:9:in `call'
actionpack (5.0.3) lib/action_dispatch/middleware/request_id.rb:24:in `call'
rack (2.0.3) lib/rack/method_override.rb:22:in `call'
rack (2.0.3) lib/rack/runtime.rb:22:in `call'
activesupport (5.0.3) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
actionpack (5.0.3) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.0.3) lib/action_dispatch/middleware/static.rb:136:in `call'
rack (2.0.3) lib/rack/sendfile.rb:111:in `call'
railties (5.0.3) lib/rails/engine.rb:522:in `call'
puma (3.8.2) lib/puma/configuration.rb:224:in `call'
puma (3.8.2) lib/puma/server.rb:600:in `handle_request'
puma (3.8.2) lib/puma/server.rb:435:in `process_client'
puma (3.8.2) lib/puma/server.rb:299:in `block in run'
puma (3.8.2) lib/puma/thread_pool.rb:120:in `block in spawn_thread'

```

Thanks
