### ISSUE TITLE
redirect-url not included in confirmation instructions email view

### ISSUE THREAD

**Issue by sburke56** [lynndylanhurley/ng-token-auth#99]
Using devise_token_auth 0.1.30
ng-token-auth#0.0.24

Here's my server output when I do a submitRegistration from the client side.  Notice that the redirect-url isn't added as a parameter to the anchor link in the email.  There is confirmation token but no redirect-url so I get a bad argument error from the server when it calls DeviseTokenAuth::ConfirmationsController#show. 

Am I seeing things right here?  I'm not sure if I'm missing a part of the configuration or is this a bug? 

```
Processing by DeviseTokenAuth::RegistrationsController#create as HTML
  Parameters: {"first_name"=>"new", "last_name"=>"person", "email"=>"steve.burke.56+a9@gmail.com", "password"=>"[FILTERED]", "password_confirmation"=>"[FILTERED]", "confirm_success_url"=>"http://localhost:3000/#/confirmed", "config_name"=>"default", "registration"=>{"first_name"=>"new", "last_name"=>"person", "email"=>"steve.burke.56+a9@gmail.com", "password"=>"[FILTERED]", "password_confirmation"=>"[FILTERED]", "confirm_success_url"=>"http://localhost:3000/#/confirmed", "config_name"=>"default"}}
Unpermitted parameters: first_name, last_name, confirm_success_url, config_name, registration
Unpermitted parameters: first_name, last_name, confirm_success_url, config_name, registration
   (0.3ms)  BEGIN
   (1.2ms)  SELECT COUNT(*) FROM "users"  WHERE "users"."provider" = 'email' AND "users"."email" = 'steve.burke.56+a9@gmail.com'
  User Load (1.1ms)  SELECT  "users".* FROM "users"  WHERE "users"."confirmation_token" = '15173d0a2d6f59f5fa6d08e56d6282da64b4a2d45f369ee265fadada429d69ff'  ORDER BY "users"."id" ASC LIMIT 1
  SQL (0.7ms)  INSERT INTO "users" ("cc_list", "confirmation_sent_at", "confirmation_token", "created_at", "email", "encrypted_password", "provider", "tokens", "uid", "updated_at") VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10) RETURNING "id"  [["cc_list", "null"], ["confirmation_sent_at", "2015-01-26 17:30:34.500131"], ["confirmation_token", "15173d0a2d6f59f5fa6d08e56d6282da64b4a2d45f369ee265fadada429d69ff"], ["created_at", "2015-01-26 17:30:34.157987"], ["email", "steve.burke.56+a9@gmail.com"], ["encrypted_password", "$2a$10$udCjhynLzHnwxKuTwXxN.eQocVVLmnPkdFJHH4H4LprHwkH35tyfq"], ["provider", "email"], ["tokens", "{}"], ["uid", "steve.burke.56+a9@gmail.com"], ["updated_at", "2015-01-26 17:30:34.157987"]]
   (11.2ms)  COMMIT
  Rendered devise/mailer/confirmation_instructions.html.erb (1.1ms)

Devise::Mailer#confirmation_instructions: processed outbound mail in 33.6ms

Sent mail to steve.burke.56+a9@gmail.com (1281.4ms)
Date: Mon, 26 Jan 2015 12:30:34 -0500
From: please-change-me-at-config-initializers-devise@example.com
Reply-To: please-change-me-at-config-initializers-devise@example.com
To: steve.burke.56+a9@gmail.com
Message-ID: <54c679ba8a0bf_17c51defd1884527@sewer.mail>
Subject: Confirmation instructions
Mime-Version: 1.0
Content-Type: text/html;
 charset=UTF-8
Content-Transfer-Encoding: 7bit
client-config: default
redirect-url: http://localhost:3000/#/confirmed

<p>Welcome steve.burke.56+a9@gmail.com!</p>

<p>You can confirm your account email through the link below:</p>

<p><a href="http://localhost:3000/api/v1/auth/confirmation?confirmation_token=e-31awoAHz224bzPsKyg">Confirm my account</a></p>

Completed 200 OK in 1810ms (Views: 0.5ms | ActiveRecord: 17.9ms)
```

After clicking on the confirmation link this is the stack trace of the error I get. 
```
/home/sburke/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/uri/common.rb:715:in `URI'
devise_token_auth (0.1.30) app/models/devise_token_auth/concerns/user.rb:196:in `generate_url'
devise_token_auth (0.1.30) app/models/devise_token_auth/concerns/user.rb:178:in `build_auth_url'
devise_token_auth (0.1.30) app/controllers/devise_token_auth/confirmations_controller.rb:20:in `show'

redirect-url not included in confirmation instructions email view
```

**Comment by sburke56** [comment]
This issue was because I had old devise views in my tree that were overriding the ng-token-auth devise views.  So when I deleted 'app/views/devise' the confirmation url was correct since it was using the ng-token-auth views.  

What I was trying to do was confirm an existing user in the database that was there when I was using devise all on the server side. I needed to do the following in the console. 

# find my user, clear confirmed, set provider, send confirmation email again 
s = User.find(1)
s.confirmed_at = ''
s.provider = 'email'
s.save
s.send_confirmation_instructions
